# Generated by Django 5.0.7 on 2024-08-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='City',
        ),
    ]
